export interface KeyMap {
    label: string;
    shiftLabel?: string;
    description?: string;
}

export interface KeyboardLayout {
    name: string;
    keys: Record<string, KeyMap>;
}

export const layouts: Record<string, KeyboardLayout> = {
    "390": {
        name: "세벌식 390",
        keys: {
            "Backquote": { label: "`", shiftLabel: "~" },
            "Digit1": { label: "ㅎ", shiftLabel: "!", description: "종성" },
            "Digit2": { label: "ㅆ", shiftLabel: "@", description: "종성" },
            "Digit3": { label: "ㅂ", shiftLabel: "#", description: "종성" },
            "Digit4": { label: "ㅛ", shiftLabel: "$", description: "중성" },
            "Digit5": { label: "ㅠ", shiftLabel: "%", description: "중성" },
            "Digit6": { label: "ㅑ", shiftLabel: "^", description: "중성" },
            "Digit7": { label: "ㅖ", shiftLabel: "&", description: "중성" },
            "Digit8": { label: "ㅢ", shiftLabel: "*", description: "중성" },
            "Digit9": { label: "ㅜ", shiftLabel: "(", description: "중성" },
            "Digit0": { label: "ㅋ", shiftLabel: ")", description: "종성" },
            "Minus": { label: "-", shiftLabel: "_" },
            "Equal": { label: "=", shiftLabel: "+" },
            "KeyQ": { label: "ㅅ", shiftLabel: "ㅍ", description: "종성" },
            "KeyW": { label: "ㄹ", shiftLabel: "ㅌ", description: "종성" },
            "KeyE": { label: "ㅕ", shiftLabel: "ㅋ", description: "중성" },
            "KeyR": { label: "ㅐ", shiftLabel: "ㅒ", description: "중성" },
            "KeyT": { label: "ㅓ", shiftLabel: ";", description: "중성" },
            "KeyY": { label: "ㄹ", shiftLabel: "7", description: "초성" },
            "KeyU": { label: "ㄷ", shiftLabel: "8", description: "초성" },
            "KeyI": { label: "ㅁ", shiftLabel: "9", description: "초성" },
            "KeyO": { label: "ㅊ", shiftLabel: "/", description: "초성" },
            "KeyP": { label: "ㅍ", shiftLabel: "*", description: "초성" },
            "BracketLeft": { label: "[", shiftLabel: "{" },
            "BracketRight": { label: "]", shiftLabel: "}" },
            "Backslash": { label: "\\", shiftLabel: "|" },
            "KeyA": { label: "ㅇ", shiftLabel: "ㄷ", description: "종성" },
            "KeyS": { label: "ㄴ", shiftLabel: "ㄶ", description: "종성" },
            "KeyD": { label: "ㅣ", shiftLabel: "ㄺ", description: "중성" },
            "KeyF": { label: "ㅏ", shiftLabel: "ㄲ", description: "중성" },
            "KeyG": { label: "ㅡ", shiftLabel: "/", description: "중성" },
            "KeyH": { label: "ㄴ", shiftLabel: "1", description: "초성" },
            "KeyJ": { label: "ㅇ", shiftLabel: "2", description: "초성" },
            "KeyK": { label: "ㄱ", shiftLabel: "3", description: "초성" },
            "KeyL": { label: "ㅈ", shiftLabel: "4", description: "초성" },
            "Semicolon": { label: "ㅂ", shiftLabel: "5", description: "초성" },
            "Quote": { label: "ㅌ", shiftLabel: "6", description: "초성" },
            "KeyZ": { label: "ㅁ", shiftLabel: "ㅊ", description: "종성" },
            "KeyX": { label: "ㄱ", shiftLabel: "ㅄ", description: "종성" },
            "KeyC": { label: "ㅔ", shiftLabel: "ㄻ", description: "중성" },
            "KeyV": { label: "ㅗ", shiftLabel: "ㅀ", description: "중성" },
            "KeyB": { label: "ㅜ", shiftLabel: "!", description: "중성" },
            "KeyN": { label: "ㅅ", shiftLabel: "0", description: "초성" },
            "KeyM": { label: "ㅎ", shiftLabel: ".", description: "초성" },
            "Comma": { label: ",", shiftLabel: "0" },
            "Period": { label: ".", shiftLabel: "=" },
            "Slash": { label: "ㅗ", shiftLabel: "?", description: "중성" }
        }
    },
    "Final": {
        name: "세벌식 최종 (391)",
        keys: {
            "Backquote": { label: "*", shiftLabel: "~" },
            "Digit1": { label: "ㅎ", shiftLabel: "!", description: "종성" },
            "Digit2": { label: "ㅆ", shiftLabel: "'", description: "종성" },
            "Digit3": { label: "ㅂ", shiftLabel: "\"", description: "종성" },
            "Digit4": { label: "ㄱ", shiftLabel: "?", description: "종성" },
            "Digit5": { label: "ㄷ", shiftLabel: ".", description: "종성" },
            "Digit6": { label: "ㅁ", shiftLabel: ",", description: "종성" },
            "Digit7": { label: "ㅅ", shiftLabel: "-", description: "종성" },
            "Digit8": { label: "ㅕ", shiftLabel: "ㅖ", description: "중성" },
            "Digit9": { label: "ㅐ", shiftLabel: "ㅒ", description: "중성" },
            "Digit0": { label: "ㅓ", shiftLabel: "ㅢ", description: "중성" },
            "Minus": { label: "ㄹ", shiftLabel: "<", description: "종성" },
            "Equal": { label: "ㅇ", shiftLabel: ">", description: "종성" },
            "KeyQ": { label: "ㅋ", shiftLabel: "1", description: "종성" },
            "KeyW": { label: "ㅌ", shiftLabel: "2", description: "종성" },
            "KeyE": { label: "ㅊ", shiftLabel: "3", description: "종성" },
            "KeyR": { label: "ㅍ", shiftLabel: "4", description: "종성" },
            "KeyT": { label: "ㅎ", shiftLabel: "5", description: "종성" },
            "KeyY": { label: "ㄹ", shiftLabel: "6", description: "초성" },
            "KeyU": { label: "ㄷ", shiftLabel: "7", description: "초성" },
            "KeyI": { label: "ㅁ", shiftLabel: "8", description: "초성" },
            "KeyO": { label: "ㅊ", shiftLabel: "9", description: "초성" },
            "KeyP": { label: "ㅍ", shiftLabel: "0", description: "초성" },
            "BracketLeft": { label: "ㅑ", shiftLabel: "(", description: "중성" },
            "BracketRight": { label: "ㅠ", shiftLabel: ")", description: "중성" },
            "Backslash": { label: "ㅛ", shiftLabel: ":", description: "중성" },
            "KeyA": { label: "ㅇ", shiftLabel: ";", description: "종성" },
            "KeyS": { label: "ㄴ", shiftLabel: "[", description: "종성" },
            "KeyD": { label: "ㅣ", shiftLabel: "]", description: "중성" },
            "KeyF": { label: "ㅏ", shiftLabel: "{", description: "중성" },
            "KeyG": { label: "ㅡ", shiftLabel: "}", description: "중성" },
            "KeyH": { label: "ㄴ", shiftLabel: "6", description: "초성" },
            "KeyJ": { label: "ㅇ", shiftLabel: "4", description: "초성" },
            "KeyK": { label: "ㄱ", shiftLabel: "5", description: "초성" },
            "KeyL": { label: "ㅈ", shiftLabel: "6", description: "초성" },
            "Semicolon": { label: "ㅂ", shiftLabel: ":", description: "초성" },
            "Quote": { label: "ㅌ", shiftLabel: "\"", description: "초성" },
            "KeyZ": { label: "ㅁ", shiftLabel: "7", description: "종성" },
            "KeyX": { label: "ㄱ", shiftLabel: "8", description: "종성" },
            "KeyC": { label: "ㅔ", shiftLabel: "9", description: "중성" },
            "KeyV": { label: "ㅗ", shiftLabel: "0", description: "중성" },
            "KeyB": { label: "ㅜ", shiftLabel: "/", description: "중성" },
            "KeyN": { label: "ㅅ", shiftLabel: "0", description: "초성" },
            "KeyM": { label: "ㅎ", shiftLabel: "1", description: "초성" },
            "Comma": { label: ",", shiftLabel: "2" },
            "Period": { label: ".", shiftLabel: "3" },
            "Slash": { label: "ㅗ", shiftLabel: "?", description: "중성" }
        }
    }
};
